### ISSUE TITLE
Using default tag: latest Error response from daemon: manifest for bradymiller/pre-openemr:latest not found

### ISSUE THREAD

**Issue by jonnalagaddda** [openemr/demo_farm_openemr#28]
Hi Brady,
     I am nagendra,i am not able to pull the your openemr project,please let me know as soon as possible,i am getting issue like ...........{issue}Using default tag: latest
Error response from daemon: manifest for bradymiller/pre-openemr:latest not found

**Comment by jonnalagaddda** [comment]
Thank you very much brady for a giving voluble information

**Comment by bradymiller** [comment]
no problem. let us know how it goes. -brady
