### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by mgifford** [openemr/demo_farm_openemr#59]
I tried to see the demo:  
  
[https://www.open-emr.org/demo/](https://www.open-emr.org/demo/)  
  
These three:

| Demo | Link |
| --- | --- |
| OpenEMR 7.0.2 Main Demo | [https://demo.openemr.io/openemr](https://demo.openemr.io/openemr/index.php) |
| Alternate Demo | [https://demo.openemr.io/a/openemr](https://demo.openemr.io/a/openemr/index.php) |
| Another Alternate Demo | [https://demo.openemr.io/b/openemr](https://demo.openemr.io/b/openemr/index.php) |

  
All gave me:  
UNABLE to open file '/var/www/localhost/htdocs/openemr/sites/default/sqlconf.php' for writing.  
  
  
None of these opened at all:

| Demo | Link |
| --- | --- |
| OpenEMR 7.0.2 Portal Demo | [https://demo.openemr.io/openemr/portal](https://demo.openemr.io/openemr/portal/index.php) |
| Alternate Demo | [https://demo.openemr.io/a/openemr/portal](https://demo.openemr.io/a/openemr/portal/index.php) |
| Another Alternate Demo | [https://demo.openemr.io/b/openemr/portal](https://demo.openemr.io/b/openemr/portal/index.php) |

  
It would be great if there were some testing to make sure these stayed up?

**Comment by stephenwaite** [comment]
https://github.com/openemr/openemr/issues/7870
